all:main

main: main.cpp
	g++ main.cpp -I /home/disk6/fangxiaoming01/xiaoming/cpp/lib/googletest/googletest/include /home/disk6/fangxiaoming01/xiaoming/cpp/lib/googletest/build/googlemock/gtest/libgtest.a -lpthread -o main
